apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  # Selector: tells the deployment how to find the all pods that it needs to create.
  selector:
    matchLabels:
      app: client
  # template: describes how to create the pods.
  template:
    metadata:
      labels:
        app: client
    # spec: tells the pod how to behave
    spec:
      # containers that are going to be runnig inside this pod
      containers:
        - name: client
          image: us.gcr.io/ticketapp-dev-499418/client
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  # tells the service how to find the set of pods that it needs to route traffic to. Find all pods with the label app=client
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
